---
title: "city_models"
author: "Isaac Goldstein"
date: "10/28/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.align = "center", fig.width=16,  message=F)
#knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(autodep = TRUE)
library(lubridate)
library(here)
library(fs)
library(tidyverse)
library(tidybayes)
library(scales)
library(patchwork)
library(glue)
library(zoo)
library(rstan)

theme_set(theme_bw(base_size =22)) 
```

```{r}

model_name <- "SEIeIpRD"
loc_name <- "oc"

source(here("code", model_name, "helper_functions.R"))
source(here("code", model_name, "plot_functions.R"))

run_analysis <- FALSE
if (run_analysis == TRUE) {
city_data <- read_csv("C:/Users/fiddl/Documents/uci_covid19_dashboard/data/oc_city_data.csv")
  
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

# Read OCHCA Data ---------------------------------------------------------
# city_data <- read.csv(here("data", "city_data.csv"))

city_data$posted_date <- as.Date(city_data$posted_date)

old_folder_name = "2020-08-17_2020-09-21"

#read in old results, this is used to calculate parameters of initial condition distributions
oc_post_old <- read_rds(here("code", model_name, loc_name, old_folder_name, "oc_post.rds"))
oc_model_objects_old <- read_rds(here("code", model_name, loc_name, old_folder_name, "model_objects.rds"))

#set start and end date of analysis
start_date <- as.Date("2020-08-28")
end_date <- as.Date("2020-10-02")

test <- city_data %>%
    filter(city == "Irvine") %>%
    filter(posted_date >= lubridate::ymd(start_date),
           posted_date <= lubridate::ymd(end_date)) %>%
    group_by(lump = as.integer(floor((max(posted_date) - posted_date) / 3))) %>%
    filter(n() == 3) %>%
    summarize(start_date = min(posted_date),
              end_date = max(posted_date),
              new_cases = sum(new_cases),
              new_tests = sum(new_tests),
              new_deaths = sum(new_deaths)) %>%
    dplyr::select(-lump) %>%
    arrange(start_date)

test2 <- city_data %>%
    filter(city == "Santa Ana") %>%
    filter(posted_date >= lubridate::ymd(start_date),
           posted_date <= lubridate::ymd(end_date)) %>%
    group_by(lump = as.integer(floor((max(posted_date) - posted_date) / 3))) %>%
    filter(n() == 3) %>%
    summarize(start_date = min(posted_date),
              end_date = max(posted_date),
              new_cases = sum(new_cases),
              new_tests = sum(new_tests),
              new_deaths = sum(new_deaths)) %>%
    dplyr::select(-lump) %>%
    arrange(start_date)


# Setup Model Objects -----------------------------------------------------

#acquire posterior samples for fraction infected, fraction infectious, fraction early infectious 
#nearest day to when current analysis starts
oc_post_old_wide <- oc_post_old %>%
  spread_draws(epi_curves[i]) %>%
  ungroup() %>%
  select(i, epi_curves, .draw) %>%
  mutate(g = (i - 1) %% oc_model_objects_old$n_curves + 1) %>%
  mutate(g_text = oc_model_objects_old$epi_curve_names[g]) %>%
  mutate(g_text = fct_reorder(g_text, g)) %>%
  mutate(t = oc_model_objects_old$dates_pp[ceiling(i / oc_model_objects_old$n_curves)]) %>%
  select(-i, - g) %>%
  pivot_wider(names_from = g_text, values_from = epi_curves)

target_date <- unique(oc_post_old_wide$t)[which.min(abs(unique(oc_post_old_wide$t) - start_date))]

for_estimating <- oc_post_old_wide %>%
  filter(t == target_date) %>%
  transmute(S=S,
            frac_carrs = 1 - S,
            frac_carrs_infec = (IE + IP) / (E + IE + IP),
            frac_infec_early = IE /(IE + IP))

#purpose: provide method of moments estimators for parameters of a beta distribution
# for the city of irvine, adjusting the mean to be proportional to reported 
# county prevalence in daniel parker's study from august 15
#param: x: draws from a beta distribution
#output: method of moment estimates for alpha and beta of a beta distribution
mom_beta_irvine <- function(x) {
  x_bar <- .91 * mean(x)
  v_bar <- var(x)

  c(alpha = x_bar * (x_bar * (1 - x_bar) / v_bar - 1),
    beta = (1 - x_bar) * (x_bar * (1 - x_bar) / v_bar - 1))
}

#same as above for santa ana
mom_beta_sa <- function(x) {
  x_bar <- 1.58 * mean(x)
  v_bar <- var(x)

  c(alpha = x_bar * (x_bar * (1 - x_bar) / v_bar - 1),
    beta = (1 - x_bar) * (x_bar * (1 - x_bar) / v_bar - 1))
}

#regular version for retrieving fraction infected and fraction infected early
mom_beta <- function(x) {
  x_bar <- mean(x)
  v_bar <- var(x)

  c(alpha = x_bar * (x_bar * (1 - x_bar) / v_bar - 1),
    beta = (1 - x_bar) * (x_bar * (1 - x_bar) / v_bar - 1))
}

frac_carrs_prior_irvine <- mom_beta_irvine(for_estimating$frac_carrs)
frac_carrs_prior_sa <- mom_beta_sa(for_estimating$frac_carrs)
frac_carrs_infec_prior <- mom_beta(for_estimating$frac_carrs_infec)
frac_infec_early_prior <- mom_beta(for_estimating$frac_infec_early)

init_func_irvine <- function() list(frac_carrs = frac_carrs_prior_irvine[1] / sum(frac_carrs_prior_irvine),
                             frac_carrs_infec = frac_carrs_infec_prior[1] / sum(frac_carrs_infec_prior),
                             frac_infec_early = frac_infec_early_prior[1] / sum(frac_infec_early_prior))


init_func_sa <- function() list(frac_carrs = frac_carrs_prior_sa[1] / sum(frac_carrs_prior_sa),
                             frac_carrs_infec = frac_carrs_infec_prior[1] / sum(frac_carrs_infec_prior),
                             frac_infec_early = frac_infec_early_prior[1] / sum(frac_infec_early_prior))

control_list <- list(adapt_delta = 0.99,
                     max_treedepth = 20)
# control_list <- list()

# update population size with median of the posterior for fraction susceptibles day before analysis start
new_pop_size_irvine <- as.integer(median(for_estimating$S) * 287401L)
new_pop_size_santa_ana <- as.integer(median(for_estimating$S) * 332318L)

city_data_irvine <- city_data %>%
  filter(city == "Irvine")

city_data_santa_ana <- city_data %>%
  filter(city == "Santa Ana")
#create model objects to input into stan, see helper_functions.R for details
model_objects_irvine <- create_model_objects(ochca_covid = city_data_irvine,
                                      first_day = start_date,
                                      last_day = end_date,
                                      time_interval_in_days = 3,
                                      forecast_in_days = 48,
                                      future_tests_per_day = 700,
                                      popsize = new_pop_size_irvine,
                                      frac_carrs_beta = frac_carrs_prior_irvine,
                                      frac_carrs_infec_beta = frac_carrs_infec_prior,
                                      frac_infec_early_beta = frac_infec_early_prior)

model_objects_santa_ana <- create_model_objects(ochca_covid = city_data_santa_ana,
                                      first_day = start_date,
                                      last_day = end_date,
                                      time_interval_in_days = 3,
                                      forecast_in_days = 48,
                                      future_tests_per_day = 700,
                                      popsize = new_pop_size_santa_ana,
                                      frac_carrs_beta = frac_carrs_prior_sa,
                                      frac_carrs_infec_beta = frac_carrs_infec_prior,
                                      frac_infec_early_beta = frac_infec_early_prior)

#create a model objects for sampling from the prior distributions, used in figure creation
model_objects_irvine_priors_only <- model_objects_irvine
model_objects_irvine_priors_only$priors_only <- T
model_objects_irvine_priors_only$forecast_in_days <- 0

model_objects_santa_ana_priors_only <- model_objects_santa_ana
model_objects_santa_ana_priors_only$priors_only <- T
model_objects_santa_ana_priors_only$forecast_in_days <- 0


# Setup Results Folder ----------------------------------------------------
folder_name_irvine <- str_c("irvine",model_objects_irvine$actual_first_day, 
                            model_objects_irvine$actual_last_day, 
                            sep = "_")
folder_loc_irvine <- here("code", model_name, "cities", folder_name_irvine)
dir_create(folder_loc_irvine)

write_rds(model_objects_irvine, file.path(folder_loc_irvine, "model_objects_irvine.rds"))

folder_name_santa_ana <- str_c("sa", model_objects_santa_ana$actual_first_day, 
                               model_objects_santa_ana$actual_last_day, 
                               sep = "_")
folder_loc_santa_ana <- here("code", model_name, "cities", folder_name_santa_ana)
dir_create(folder_loc_santa_ana)

write_rds(model_objects_santa_ana, file.path(folder_loc_santa_ana, "model_objects_santa_ana.rds"))

# Sample Posterior --------------------------------------------------------
oc_post_irvine <- stan(file = here("code", model_name, str_c(model_name, ".stan")),
                data = model_objects_irvine,
                init = init_func_irvine,
                seed = 0,
                chains = 4,
                control = control_list)

write_rds(oc_post_irvine, file.path(folder_loc_irvine, "oc_post_irvine.rds"))


# Sample Prior ------------------------------------------------------------
oc_prior_irvine <- stan(file = here("code", model_name, str_c(model_name, ".stan")),
                 data = model_objects_irvine_priors_only,
                 init = init_func_irvine,
                 seed = 0,
                 chains = 4,
                 control = control_list)

write_rds(oc_prior_irvine, file.path(folder_loc_irvine, "oc_prior_irvine.rds"))


# Sample Posterior --------------------------------------------------------
oc_post_santa_ana <- stan(file = here("code", model_name, str_c(model_name, ".stan")),
                data = model_objects_santa_ana,
                init = init_func_sa,
                seed = 0,
                chains = 4,
                control = control_list)

write_rds(oc_post_santa_ana, file.path(folder_loc_santa_ana, "oc_post_santa_ana.rds"))


# Sample Prior ------------------------------------------------------------
oc_prior_santa_ana <- stan(file = here("code", model_name, str_c(model_name, ".stan")),
                 data = model_objects_santa_ana_priors_only,
                 init = init_func_sa,
                 seed = 0,
                 chains = 4,
                 control = control_list)

write_rds(oc_prior_santa_ana, file.path(folder_loc_santa_ana, "oc_prior_santa_ana.rds"))
}
```

```{r reading-model-objects, cache=TRUE}
# Pick folder to build model from. Defaults to most recent end date with earliest start date
model_name <- "SEIeIpRD"
loc_name <- "cities"

source(here("code", model_name, "helper_functions.R"))
source(here("code", model_name, "plot_functions.R"))

folder_name_irvine <-"irvine_2020-09-25_2020-10-30"
folder_name_sa <-"sa_2020-09-25_2020-10-30"

folder_loc_irvine <- here("code", model_name, loc_name, folder_name_irvine)
folder_loc_sa <- here("code", model_name, loc_name, folder_name_sa)

oc_post_irvine <- read_rds(file.path(folder_loc_irvine, "oc_post_irvine.rds"))
model_objects_irvine <- read_rds(file.path(folder_loc_irvine, "model_objects_irvine.rds"))
oc_prior_irvine <- read_rds(file.path(folder_loc_irvine, "oc_prior_irvine.rds"))

oc_post_santa_ana <- read_rds(file.path(folder_loc_sa, "oc_post_santa_ana.rds"))
model_objects_santa_ana <- read_rds(file.path(folder_loc_sa, "model_objects_santa_ana.rds"))
oc_prior_santa_ana <- read_rds(file.path(folder_loc_sa, "oc_prior_santa_ana.rds"))

lumped_ochca_covid_sa <- model_objects_santa_ana$lumped_ochca_covid
time_interval_in_days_sa <- model_objects_santa_ana$time_interval_in_days

lumped_ochca_covid_irvine <- model_objects_irvine$lumped_ochca_covid
time_interval_in_days_irvine <- model_objects_irvine$time_interval_in_days


theme_set(theme_bw(base_size =22)) 

```

```{r executive-summary, warning=FALSE, cache=TRUE}
R0_bci_irvine = oc_post_irvine %>% spread_draws(log_R0) %>% mutate(R0=exp(log_R0))%>% median_qi(R0) %>% mutate_if(is.numeric, signif, 2)

R_eff_bci_irvine <- spread_draws(oc_post_irvine, log_R0) %>%
  dplyr::select(.draw, log_R0) %>%
  left_join(prep_epi_curves(oc_post_irvine, model_objects_irvine) %>%
              filter(g_text == "S",
                     t == model_objects_irvine$actual_last_day) %>%
              ungroup() %>%
              select(S = epi_curves, .draw)) %>%
  transmute(Reff = exp(log_R0) * S) %>% 
  median_qi(Reff) %>% 
  mutate_if(is.numeric, signif, 2)

IFR_bci_irvine = oc_post_irvine %>% spread_draws(IFR) %>% median_qi(IFR) %>% mutate_if(is.numeric, signif, 2)

rho_death_bci_irvine = oc_post_irvine %>% spread_draws(rho_death) %>% median_qi(rho_death) %>% mutate_if(is.numeric, signif, 2)

ci_width <- 0.95
prepped_cumulative_inc_irvine <- prep_cumulative_inc(model_objects_irvine, oc_post_irvine)

death_inc_summaries_irvine <- prepped_cumulative_inc_irvine$posterior %>% 
  filter(usage == "train") %>%
  dplyr::select(-usage) %>% 
  group_by(t, name) %>% 
  median_qi(.width = ci_width) %>% 
  left_join(prepped_cumulative_inc_irvine$observed) %>% 
  mutate(ratio_l = .lower / observed) %>%
  mutate(ratio_u = .upper / observed) %>% 
  group_by(name) %>%
  filter(t == max(t)) %>%
  select(name, c(t, ratio_l, ratio_u, .lower, .upper, observed)) %>%
  mutate_if(is.numeric, signif, 2) %>%
  column_to_rownames(var = "name")

R0_bci_sa = oc_post_santa_ana %>% spread_draws(log_R0) %>% mutate(R0=exp(log_R0))%>% median_qi(R0) %>% mutate_if(is.numeric, signif, 2)

R_eff_bci_sa <- spread_draws(oc_post_santa_ana, log_R0) %>%
  select(.draw, log_R0) %>%
  left_join(prep_epi_curves(oc_post_santa_ana, model_objects_santa_ana) %>%
              filter(g_text == "S",
                     t == model_objects_santa_ana$actual_last_day) %>%
              ungroup() %>%
              select(S = epi_curves, .draw)) %>%
  transmute(Reff = exp(log_R0) * S) %>% 
  median_qi(Reff) %>% 
  mutate_if(is.numeric, signif, 2)

IFR_bci_sa = oc_post_santa_ana %>% spread_draws(IFR) %>% median_qi(IFR) %>% mutate_if(is.numeric, signif, 2)

rho_death_bci_sa = oc_post_santa_ana %>% spread_draws(rho_death) %>% median_qi(rho_death) %>% mutate_if(is.numeric, signif, 2)

ci_width <- 0.95
prepped_cumulative_inc_sa <- prep_cumulative_inc(model_objects_santa_ana, oc_post_santa_ana)

death_inc_summaries_sa <- prepped_cumulative_inc_sa$posterior %>% 
  filter(usage == "train") %>%
  dplyr::select(-usage) %>% 
  group_by(t, name) %>% 
  median_qi(.width = ci_width) %>% 
  left_join(prepped_cumulative_inc_sa$observed) %>% 
  mutate(ratio_l = .lower / observed) %>%
  mutate(ratio_u = .upper / observed) %>% 
  group_by(name) %>%
  filter(t == max(t)) %>%
  select(name, c(t, ratio_l, ratio_u, .lower, .upper, observed)) %>%
  mutate_if(is.numeric, signif, 2) %>%
  column_to_rownames(var = "name")

```

```{r, R0-IFR-violin, warning=FALSE, cache=TRUE}
# create two data sets, one with r0 the other with ifr for both counties
prior_r0 <- oc_prior_irvine %>%
  spread_draws(log_R0) %>%
  mutate(R0 = exp(log_R0),
         Type = "Prior") %>%
  dplyr::select(R0, Type) %>%
  filter(R0 < 3)

irvine_r0 <- oc_post_irvine %>%
  spread_draws(log_R0) %>%
  mutate(R0 = exp(log_R0),
         Type = "Irvine") %>%
  dplyr::select(R0, Type)

sa_r0 <- oc_post_santa_ana %>%
  spread_draws(log_R0) %>%
  mutate(R0 = exp(log_R0),
         Type = "Santa Ana") %>%
  dplyr::select(R0, Type)

r0_data <- rbind(prior_r0, irvine_r0, sa_r0)

r0_data$Type <- factor(r0_data$Type, levels = c("Prior", "Irvine", "Santa Ana"))
r0_plot <- r0_data%>%
  ggplot(aes(Type, R0)) +
  stat_eye(fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4") + 
  xlab("Prior and Posteriors by City")+
  ylab(expression(R[0])) +
  ylim(c(0, 3))
  geom_hline(yintercept = 1, linetype = "dashed") 

prior_IFR <- oc_prior_irvine %>%
  spread_draws(IFR) %>%
  mutate(Type = "Prior") %>%
  dplyr::select(IFR, Type)

irvine_IFR <- oc_post_irvine %>%
  spread_draws(IFR) %>%
  mutate(Type = "Irvine") %>%
  dplyr::select(IFR, Type)

sa_IFR <- oc_post_santa_ana %>%
  spread_draws(IFR) %>%
  mutate(Type = "Santa Ana") %>%
  dplyr::select(IFR, Type)

IFR_data <- rbind(prior_IFR, irvine_IFR, sa_IFR)

IFR_data$Type <- factor(IFR_data$Type, levels = c("Prior", "Irvine", "Santa Ana"))
IFR_plot <- IFR_data %>%
  ggplot(aes(Type, IFR)) +
  stat_eye(fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4") + 
  xlab("Prior and Posteriors by City")+
  ylab("IFR") +
  ylim(c(0, max(IFR_data$IFR)))
  geom_hline(yintercept = 1, linetype = "dashed") 

city_param_plot <- r0_plot / IFR_plot +
  plot_annotation(title = "R0 and IFR in two cities in Orange County, CA", 
                  subtitle = "Sept 25 through Oct 30")

ggsave(filename = "city_parameters_plot.pdf", plot = city_param_plot, device = "pdf", path = here("code", "SEIeIpRD"), width = 8.5, height = 8, units = "in")
```

```{r latent-vs-observed-incidence, warning=FALSE, cache=TRUE}
ci_width <- c(0.5, 0.8, 0.95)
prepped_cumulative_inc_irvine <- map(prepped_cumulative_inc_irvine, ~mutate(., name = str_replace(name,
                                  "(Cumulative.+)",
                                  str_c("\\1\nSince ", format(model_objects_irvine$actual_first_day, "%b %d")))))
ggplot() +
  geom_lineribbon(data = prepped_cumulative_inc_irvine$posterior %>% 
                    group_by(t, name, usage) %>% 
                    median_qi(.width = ci_width),
  mapping = aes(t, value, ymin = .lower, ymax = .upper), size=1.5,
  color = "steelblue4") +
  geom_col(data = prepped_cumulative_inc_irvine$observed %>%
             filter(usage == "train"),
           mapping = aes(x = t, y = observed),
           fill = "black") +
  facet_wrap(. ~ name, scales = "free_y", strip.position="left") +
  ggtitle(str_c("Irvine latent & observed trajectories, posterior median &", str_c(percent(ci_width), collapse = ", "), "credible intervals", sep = " ")) +
  xlab("Date") +
  ylab(NULL) +
  theme(strip.background = element_blank(),
           strip.placement = "outside", 
        strip.text = element_text(size = 22),
        legend.position = c(0.092, 0.9), legend.title = element_text(size=15.5), legend.text = element_text(size=15.5), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("21 day"), date_labels = "%b %d") +
  scale_y_continuous(labels = comma)

prepped_cumulative_inc_sa <- map(prepped_cumulative_inc_sa, ~mutate(., name = str_replace(name,
                                  "(Cumulative.+)",
                                  str_c("\\1\nSince ", format(model_objects_santa_ana$actual_first_day, "%b %d")))))
ggplot() +
  geom_lineribbon(data = prepped_cumulative_inc_sa$posterior %>% 
                    group_by(t, name, usage) %>% 
                    median_qi(.width = ci_width),
  mapping = aes(t, value, ymin = .lower, ymax = .upper), size=1.5,
  color = "steelblue4") +
  geom_col(data = prepped_cumulative_inc_sa$observed %>%
             filter(usage == "train"),
           mapping = aes(x = t, y = observed),
           fill = "black") +
  facet_wrap(. ~ name, scales = "free_y", strip.position="left") +
  ggtitle(str_c("Santa Ana latent & observed trajectories, posterior median &", str_c(percent(ci_width), collapse = ", "), "credible intervals", sep = " ")) +
  xlab("Date") +
  ylab(NULL) +
  theme(strip.background = element_blank(),
           strip.placement = "outside", 
        strip.text = element_text(size = 22),
        legend.position = c(0.092, 0.9), legend.title = element_text(size=15.5), legend.text = element_text(size=15.5), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("21 day"), date_labels = "%b %d") +
  scale_y_continuous(labels = comma)
```

```{r R0-IFR, echo=FALSE, cache=TRUE}
# If you want to plot R0 by istelf with custom lims, use this:
R0_irvine <- oc_prior_irvine %>%
  spread_draws(log_R0) %>%
  mutate(R0=exp(log_R0))%>%
  dplyr::select(-starts_with(".")) %>%
  mutate(dist = "Prior") %>%
  bind_rows(oc_post_irvine %>%
              spread_draws(log_R0)%>% mutate(R0=exp(log_R0)) %>%
              dplyr::select(-starts_with(".")) %>%
              mutate(dist = "Posterior")) %>%
  ggplot(aes(x = R0, y = dist), fill = stat(x > 1.0)) +
  stat_halfeye(normalize= "xy", fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4", slab_size = 0.5) +
  geom_vline(xintercept = 1.0, linetype = "dashed") +
  ylab(NULL) +
  xlab(expression(R[0])) +
  coord_cartesian(xlim = c(0, 2.5))

IFR_irvine <- oc_prior_irvine %>%
  spread_draws(IFR) %>% 
  select(-starts_with(".")) %>% 
  mutate(dist = "Prior") %>% 
  bind_rows(oc_post_irvine %>%
              spread_draws(IFR) %>% 
              select(-starts_with(".")) %>% 
              mutate(dist = "Posterior"))  %>%
  ggplot(aes(x =IFR, y = dist), fill = stat(x > 1.0)) +
  stat_halfeye(normalize= "xy", fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4", slab_size = 0.5) +
  #geom_vline(xintercept = 1.0, linetype = "dashed") +
  ylab(NULL) +
  xlab("Infection-to-fatality ratio (IFR)") +
  coord_cartesian(xlim = c(0, .03))

param_plot_irvine <- R0_irvine + IFR_irvine +
    plot_annotation(title = expression(paste('Irvine Prior and Posterior Summaries for ', R[0], ' and IFR')),theme=theme(plot.title = element_text(hjust = 0.14)))

R0_sa <- oc_prior_santa_ana %>%
  spread_draws(log_R0) %>%
  mutate(R0=exp(log_R0))%>%
  dplyr::select(-starts_with(".")) %>%
  mutate(dist = "Prior") %>%
  bind_rows(oc_post_santa_ana %>%
              spread_draws(log_R0)%>% mutate(R0=exp(log_R0)) %>%
              dplyr::select(-starts_with(".")) %>%
              mutate(dist = "Posterior")) %>%
  ggplot(aes(x = R0, y = dist), fill = stat(x > 1.0)) +
  stat_halfeye(normalize= "xy", fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4", slab_size = 0.5) +
  geom_vline(xintercept = 1.0, linetype = "dashed") +
  ylab(NULL) +
  xlab(expression(R[0])) +
  coord_cartesian(xlim = c(0, 2.5))

IFR_sa <- oc_prior_santa_ana %>%
  spread_draws(IFR) %>% 
  select(-starts_with(".")) %>% 
  mutate(dist = "Prior") %>% 
  bind_rows(oc_post_santa_ana %>%
              spread_draws(IFR) %>% 
              select(-starts_with(".")) %>% 
              mutate(dist = "Posterior"))  %>%
  ggplot(aes(x =IFR, y = dist), fill = stat(x > 1.0)) +
  stat_halfeye(normalize= "xy", fill="lightskyblue1", slab_color ="lightskyblue4", color="dodgerblue4", slab_size = 0.5) +
  #geom_vline(xintercept = 1.0, linetype = "dashed") +
  ylab(NULL) +
  xlab("Infection-to-fatality ratio (IFR)") +
  coord_cartesian(xlim = c(0, .03))

param_plot_sa <- R0_sa + IFR_sa +
    plot_annotation(title = expression(paste('Santa Ana Prior and Posterior Summaries for ', R[0], ' and IFR')),theme=theme(plot.title = element_text(hjust = 0.14)))

param_plot_irvine
param_plot_sa
```

```{r, cache=TRUE}
ci_width <- c(0.5, 0.8, 0.95)
prepped_death_irvine <- prep_death(model_objects_irvine, oc_post_irvine, ci_width)

death_plot_irvine <- ggplot() +
  geom_lineribbon(data = prepped_death_irvine$posterior %>% 
                    group_by(t) %>% 
                    median_qi(.width = ci_width),
                  mapping = aes(t, deaths, ymin = .lower, ymax = .upper),
                  size = 1.5,
                  color = "steelblue4") +
  geom_point(data = prepped_death_irvine$observed,
             mapping = aes(t, observed), size=2,
             fill = "black") +
  #ggtitle("Deaths due to COVID-19") +
  xlab("Date") +
  ylab("Number of Deaths") +
  theme(legend.position = c(0.75, 0.8), legend.title = element_text(size=16), legend.text = element_text(size=16), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("14 day"), date_labels = "%b %d")

prepped_pos_irvine <- prep_pos(model_objects_irvine, oc_post_irvine, ci_width)

positivity_plot_irvine <- ggplot() +
  geom_lineribbon(data = prepped_pos_irvine$posterior %>% 
                    group_by(t) %>% 
                    median_qi(.width = ci_width),
                  mapping = aes(t, percent_positive, ymin = .lower, ymax = .upper),
                  size = 1.5, color = "steelblue4") +
  geom_point(data = prepped_pos_irvine$observed,
             mapping = aes(t, observed), size=2,
             fill = "black") +
  #ggtitle("Fraction of Positive COVID-19 Tests") +
  xlab("Date") +
  ylab("Positivity Percent") +
  scale_y_continuous(labels = percent) +
  theme(legend.position = "none", legend.title = element_text(size=16), legend.text = element_text(size=16), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("14 day"), date_labels = "%b %d")


death_pos_irvine <- death_plot_irvine + positivity_plot_irvine +   
  plot_annotation(title = 'Irvine Observed & Predicted Deaths and Positive Test Percent in 3 Day Periods', theme=theme(plot.title = element_text(hjust = 0.2)))

# santa ana
prepped_death_sa<- prep_death(model_objects_santa_ana, oc_post_santa_ana, ci_width)

death_plot_sa<- ggplot() +
  geom_lineribbon(data = prepped_death_sa$posterior %>% 
                    group_by(t) %>% 
                    median_qi(.width = ci_width),
                  mapping = aes(t, deaths, ymin = .lower, ymax = .upper),
                  size = 1.5,
                  color = "steelblue4") +
  geom_point(data = prepped_death_sa$observed,
             mapping = aes(t, observed), size=2,
             fill = "black") +
  #ggtitle("Deaths due to COVID-19") +
  xlab("Date") +
  ylab("Number of Deaths") +
  theme(legend.position = c(0.75, 0.8), legend.title = element_text(size=16), legend.text = element_text(size=16), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("14 day"), date_labels = "%b %d")

prepped_pos_sa <- prep_pos(model_objects_santa_ana, oc_post_santa_ana, ci_width)

positivity_plot_sa <- ggplot() +
  geom_lineribbon(data = prepped_pos_sa$posterior %>% 
                    group_by(t) %>% 
                    median_qi(.width = ci_width),
                  mapping = aes(t, percent_positive, ymin = .lower, ymax = .upper),
                  size = 1.5, color = "steelblue4") +
  geom_point(data = prepped_pos_sa$observed,
             mapping = aes(t, observed), size=2,
             fill = "black") +
  #ggtitle("Fraction of Positive COVID-19 Tests") +
  xlab("Date") +
  ylab("Positivity Percent") +
  scale_y_continuous(labels = percent) +
  theme(legend.position = "none", legend.title = element_text(size=16), legend.text = element_text(size=16), legend.background = element_rect(fill="transparent")) + 
  scale_fill_brewer(name="Credibility level", labels=str_c(percent(rev(ci_width))), guide = guide_legend(title.position = "top", direction = "horizontal")) +
  scale_x_date(breaks=c("14 day"), date_labels = "%b %d")


death_pos_sa <- death_plot_sa + positivity_plot_sa +   
  plot_annotation(title = 'Santa Ana Observed & Predicted Deaths and Positive Test Percent in 3 Day Periods', theme=theme(plot.title = element_text(hjust = 0.2)))

death_pos_irvine
death_pos_sa

```

