---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## About

This website provides reports on the dynamics and future trends of spread of SARS-CoV-2 in Orange County, CA. Please visit the [github](https://github.com/vnminin/uci_covid_modeling) for details on the code, and read the [manuscript](https://arxiv.org/abs/2009.02654) associated with this endeavor for further methodological details.

### Authors

Damon Bayer, Isaac Goldstein, and Vladimir N. Minin<br>
Department of Statistics, University of California, Irvine

Jon Fintzi, Keith Lumbard, and Emily Ricotta<br>
National Institute of Allergy and Infectious Diseases

Richard Chhuon, Alissa Dratch, Matthew Zahn<br>
Orange County Health Care Agency

### Contact
[Vladimir Minin](https://vnminin.github.io/)  

## Methodology

### Data
We use data provided by [OCHCA](https://www.ochealthinfo.com). An aggregated version of our data is available in the [github](https://github.com/vnminin/uci_covid_modeling/tree/master/data). Crucially, we exclude repeat tests given to patients who test positive (which happens when patients are hospitalized). Our data may not correspond with publicly available data. 

We also do not analyze data in real time. This is because case, test, and death counts are often updated retroactively, and we wish to give data collectors time to provide complete results. Typically, there will be at least a ten day gap between the present day and the final date analyzed in the most recent report. 

### Statistical methodology
Our analysis relies on a six compartment mechanistic model of the pandemic. We then use Bayesian inference to provide inference on key disease dynamics and make predictions on future observed cases and deaths. Further descriptions of the methodology are available in the [manuscript](https://arxiv.org/abs/2009.02654).

### Software
We used the [R](https://www.r-project.org/) software environment, [tidyverse](https://www.tidyverse.org/) and [workflowr](https://jdblischak.github.io/workflowr/) packages for this website. Our analysis was conducted in [Stan](https://mc-stan.org/) with the [rstan](https://mc-stan.org/users/interfaces/rstan) package. 
